name: Build create feature table Container
on:
  push:
    branches:
      - main
      - dev
      - "feature/*"

env:
  REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  REPOSITORY: id-graph-api

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ env.IMAGE_FOLDER }}

      - name: Test with pytest
        run: |
          pytest --cov-report term-missing --cov=src -vv

  build:
    name: Build
    runs-on: self-hosted
    needs: test
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0

      - name: Login to container Registry
        run: |
          az login --identity
          az acr login --name ${REGISTRY}
          
      - name: Docker Build and Push "development"
        env:
          ALTERNATIVE_TAG: latest
        run: |
          export IMAGE_NAME="${REGISTRY}/${REPOSITORY}"
          IMAGE_TAG="${GITHUB_SHA:0:8}"

          # Build and push
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
          docker push ${IMAGE_NAME}:${IMAGE_TAG}

          # Push with alternative tag
          docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:${ALTERNATIVE_TAG}
          docker push ${IMAGE_NAME}:${ALTERNATIVE_TAG}

          docker logout ${REGISTRY}

  deploy-web-app:
    environment: sandbox
    runs-on: self-hosted
    needs: [build]

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      - name: Azure Login
        run: |
          az login --identity
          
      - name: Deploy App
        env:
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
          WEB_APP_NAME: ${{ secrets.WEB_APP_NAME }}
        run: |
          az webapp config container set \
            --docker-custom-image-name "${REGISTRY}/${REPOSITORY}:${GITHUB_SHA:0:8}" \
            --name "$WEB_APP_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --subscription "$SUBSCRIPTION_ID"

          az resource update \
            --ids "/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.Web/sites/${WEB_APP_NAME}/config/web" \
            --set properties.acrUseManagedIdentityCreds=True

